env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  custom-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Specify exact version

      # Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: ${{ runner.os }}-build-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Print environment variables
        run: printenv

      - name: Run build script
        run: |
          echo "Building..."
          ./build.sh 2>&1 | tee build.log
        continue-on-error: true

      - name: Capture build logs
        if: failure()
        run: cat build.log

      # Improved error handling
      - name: Archive build logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: build.log
